### ISSUE TITLE
integrate with library(tap)

### ISSUE THREAD

**Issue by mndrix** [nicoabie/quickcheck#4]
Make it easier to write quickcheck properties in a library(tap) test and have the output work correctly.  Each property should be a test.  A failing test should display the counter example in TAP comments using the standard format.

**Comment by nicoabie** [comment]
See [tap integrarion tests](https://github.com/nicoabie/quickcheck/blob/master/tests/integration/tap.pl) it outputs counter example if needed.

```bash
$ swipl -q -s tests/integration/tap.pl -g main
TAP version 13
1..2
# 100 tests OK
ok 1 - always succeeds
# Shrinking to depth 2
# Failed test prop_nonsense([0]:list(integer),[]:list(integer))
ok 2 - always fails

# tests 2
# pass  2
```
