### ISSUE TITLE
integrate with PlUnit

### ISSUE THREAD

**Issue by mndrix** [nicoabie/quickcheck#5]
Make it easier to use quickcheck properties from PlUnit tests.

**Comment by nicoabie** [comment]
@mndrix whenever you have some time, do you have an example of what you meant with this? 

See [plunit tests](https://github.com/nicoabie/quickcheck/blob/master/tests/arbitrary/negative_integer.pl)

```bash
$ make test
% PL-Unit: arbitrary_float 10000 tests OK
. done
% PL-Unit: arbitrary_negative_integer Shrinking to depth 0
Failed test prop_negative_integer(1:negative_integer)
ERROR: /data/Users/ngallinal/Development/quickcheck/tests/arbitrary/negative_integer.pl:7:
	test negative integer must be strictly lower than zero: failed

 done
% 1 test failed
% 1 tests passed
ERROR: -g run_tests,halt(0): false
```

**Comment by mndrix** [comment]
It's been so long that I don't remember exactly what I had in mind.  Sorry.

**Comment by nicoabie** [comment]
Closing this issue as it is now working with plunit.
